version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/app
      # - /app/node_modules
      - ./node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 6001:6000 # API
      - 9229:9229 # Debug
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5555:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6444:6444
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always

volumes:
  pgdata:
  redisdata:
