version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.production
    volumes:
      - .:/app
      # - /app/node_modules
      - ./node_modules:/app/node_modules
    network_mode: host
    command: sh -c "npm run migrate:prod && npm run start:prod"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env.production
    network_mode: host        # 👈 обязательно
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chopp
    volumes:
      - pgdata:/var/lib/postgresql/data
    # restart: always #чтобы отловить почему падает БД
 
  redis:
    container_name: redis
    image: redis:7-alpine
    network_mode: host        # 👈 обязательно
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always

volumes:
  pgdata:
  redisdata:
